#! /usr/bin/env bash
set -e

HERE="$(readlink -f "$(dirname "$0")")"

# Wayland plugin is not packaged, so defining this to get rid of the warning
export QT_QPA_PLATFORM=xcb

if [ "$1" = "--exec" ]; then
    BINARY_NAME="$2"
    ARGS="${@:3}"
    if [ -e "$HERE/usr/bin/$BINARY_NAME" ] ; then
        exec "$HERE/usr/bin/$BINARY_NAME" $ARGS
    else
        echo "$BINARY_NAME does not exist!"
        exit 1
    fi
elif [ ! -z $APPIMAGE ] ; then
    BINARY_NAME=$(basename "$ARGV0")
    ARGS="$@"
    if [ -e "$HERE/usr/bin/$BINARY_NAME" ] ; then
        # Replace the app image env with the symlink as it will be used
        # to create an autostart script
        SYMLINK_PATH="$(realpath -s "$ARGV0")"
        APPIMAGE=$SYMLINK_PATH exec "$HERE/usr/bin/$BINARY_NAME" $ARGS
    else
        exec "$HERE/usr/bin/MoonDeckBuddy" $ARGS
    fi
else
    ARGS="$@"
    exec "$HERE/usr/bin/MoonDeckBuddy" $ARGS
fi